### ISSUE TITLE
Issue with pyarrow

### ISSUE THREAD

**Issue by gf777** [nanoporetech/Pore-C-Snakemake#18]
Hi,

the snakemake environment has an issue with pyarrow (running .test case). 

Error : ImportError: liborc.so
In: results.test/logs/results.test/basecall/NlaIII_run02.rd.catalog.yaml.log

Looks like one of the conda environments is broken now. Apparently it could be due to recent updates in pyarrow (https://issues.apache.org/jira/browse/ARROW-10152).

When I manually install pyarrow 1.0.1 making sure I use conda-forge:

```
conda activate /vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d
conda install -c conda-forge pyarrow=1.0.1
```

this error is apparently gone, but get this new error:

```
Reads processed: 0 reads [00:00, ? reads/s]Traceback (most recent call last):
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/bin/pore_c", line 10, in <module>
    sys.exit(cli())
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/pore_c/cli.py", line 281, in prepare
    **path_kwds,
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/pore_c/analyses/reads.py", line 70, in prepare_fastq
    metadata_df = pd.concat(df_sink, ignore_index=True)
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 295, in concat
    sort=sort,
  File "/vggpfs/fs3/vgl/scratch/gformenti/porec/Pore-C-Snakemake/.snakemake/conda/f18ca46d/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 342, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

I have also tried the git of 2019, before your last commit of about 1 month ago, but due to versions not being specified for packages it also appears to be broken (it worked a few months back).

Could you please check this and fix the issue with conda if needed?

Thanks

**Comment by eharr** [comment]
I just merged a fix to master - would you mind giving it a go?

**Comment by gf777** [comment]
You got it! All good. Closing, thanks!
