### ISSUE TITLE
Missing input files for rule all:

### ISSUE THREAD

**Issue by GeoMicroSoares** [nanoporetech/Pore-C-Snakemake#29]
Hi there @eharr ,

I'm getting the following after running `snakemake --use-conda -j 10 --dry-run`:

```
Building DAG of jobs...
MissingInputException in line 42 of /mnt/drive/Pore-C-Snakemake/Snakefile:
Missing input files for rule all:
results/basecall/DpnII_run_1.rd.catalog.yaml
results/basecall/DpnII_run_2.rd.catalog.yaml
```
I really can't figure out how this `catalog.yaml` file is created, so I'm not sure how to fix this. `DpnII` is listed by Biopython, so this shouldn't be an issue... Below are my config files - hopefully someone can spot something going wrong?

 - `config/basecalls.tsv`:
 ```
 run_id enzyme refgenome_ids biospecimen fastq_path fast5_directory      sequencing_summary_path
run_1 DpnII Bs_p29 NA ../prelim_check.d/run_1712021.fastq     ../raw.d/run_1712021/all_fast5/       ../raw.d/run_1712021/sequencing_summary.txt
run_2 DpnII draft1 NA ../prelim_check.d/run_1712021.fastq     ../raw.d/run_1712021/all_fast5/       ../raw.d/run_1712021/sequencing_summary.txt
```
 - `config/references.tsv`:
 ```
 refgenome_id refgenome_path
Bs_p29 ../prelim_check.d/reference.fasta
draft1 ../prelim_check.d/reference.fasta
```
 I didn't change `config/config.yaml` or `file_layout.yaml`, just deleted `phased_vcfs.tsv` as I'm not using that.

Thanks in advance.

**Comment by LynnLy** [comment]
Hi @GeoMicroSoares,

The pipeline is expecting the run_id and enzyme to not contain any underscores, since those are being used to delimit the wildcards in the output file names. Can you change the run_ids from run_1 and run_2 to run1 and run2?

**Comment by GeoMicroSoares** [comment]
Hi @LynnLy - thanks, that solved it! Getting an error with `rule add_refgenome` now though, where my `results/logs/results/refgenome/Bsp29.rg.catalog.yaml.log` gets me what's below. Have you seen this before?

```
2022-01-14 08:01:33,972 - pore_c - INFO - Adding reference genome under prefix: results/refgenome/Bsp29.rg
[E::fai_build_core] Format error, unexpected "T" at line 1
Traceback (most recent call last):
  File "/mnt/drive/Pore-C-Snakemake/.snakemake/conda/ad5d738e/bin/pore_c", line 10, in <module>
    sys.exit(cli())
  File "/mnt/drive/Pore-C-Snakemake/.snakemake/conda/ad5d738e/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/drive/Pore-C-Snakemake/.snakemake/conda/ad5d738e/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/drive/Pore-C-Snakemake/.snakemake/conda/ad5d738e/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/drive/Pore-C-Snakemake/.snakemake/conda/ad5d738e/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/drive/Pore-C-Snakemake/.snakemake/conda/ad5d738e/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/drive/Pore-C-Snakemake/.snakemake/conda/ad5d738e/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/drive/Pore-C-Snakemake/.snakemake/conda/ad5d738e/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/drive/Pore-C-Snakemake/.snakemake/conda/ad5d738e/lib/python3.8/site-packages/pore_c/cli.py", line 135, in prepare
    pysam.faidx(str(dest_fasta))
  File "/mnt/drive/Pore-C-Snakemake/.snakemake/conda/ad5d738e/lib/python3.8/site-packages/pysam/utils.py", line 69, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[faidx] Could not build fai index results/refgenome/Bsp29.rg.fa.fai\n'
```

**Comment by stasys-hub** [comment]
@LynnLy Could you specify how and where the run_id should be changed? Just in the folder structure?

**Comment by LynnLy** [comment]
Hi @stasys-hub,

You shouldn't need to change the name of any existing files. The run_id that you specify in the first column of `config/basecalls.tsv` determines the names of the output files, and must not contain any underscores. Pore-C-Snakemake will read the file specified in the "fastq_path" column (which can be named anything) to create smaller fastq files with the naming structure: `basecall/{enzyme}_{run_id}.rd.{batch_id}.fq.gz`.

**Comment by stasys-hub** [comment]
Thank you very much, @LynnLy ! Gonna try that today.

**Comment by stasys-hub** [comment]
@LynnLy, that solved my problems! Thank you!
