### ISSUE TITLE
issue with hic text file conversion

### ISSUE THREAD

**Issue by antarikshtyagi** [nanoporetech/Pore-C-Snakemake#4]
Hi,

I need your help regarding an error in using the pore C pipleline.
I am struggling with a problem with converting the hic .text file to .hic format using juicer tools. I got this file after running poreC snakemake pipeline. Here is the command and the error without restriction site file input:

$  java -jar juicer_tools.jar pre HindIII_run01_GRCh38.hic.txt HindIII_run01_GRCh38.hic hg38
Not including fragment map
Start preprocess
Writing header
Writing body
java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.
        at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.mergeAndWriteBlocks(Preprocessor.java:1650)
        at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.access$000(Preprocessor.java:1419)
        at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:832)
        at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:582)
        at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:346)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:116)
        at juicebox.tools.HiCTools.main(HiCTools.java:96)

This is the error when running with the restriction site file:

java -Xmx2g -jar juicer_tools.jar pre -f HindIII_GRCh38.hicRef HindIII_run01_GRCh38.hic.txt HindIII_run01_GRCh38.hic hg38
Problem with creating fragment-delimited maps, NullPointerException.
This could be due to a null fragment map or to a mismatch in the chromosome name in the fragment map vis-a-vis the input file or chrom.sizes file.
Exiting.

I want to use the .hic file for visualization in juicebox. Please let me know what is causing this error.

Thanks

Antariksh

**Comment by proinde** [comment]
Greetings Antariksh,

In order to provide maximum flexibility for downstream applications, pore-c-snakemake generates .hicREF and .sizes files for use with the juicer_tools.jar pre command in place of the hg38 built-in restriction fragment maps, that way pore-c-snakemake users can try out pore-c on any reference they would like, beyond juicer's built-in reference genomes. in order to generate the .hic binary, you'll need to specify the reference digest file (found in the same folder the text .hic.txt file is located, which you have correctly included in your command) as well as the chromosome sizes file as that last positional argument (this file is found at results/refgenome/*.rg.chromsizes). The command you want would therefore be `java -Xmx2g -jar juicer_tools.jar pre -f HindIII_GRCh38.hicRef HindIII_run01_GRCh38.hic.txt HindIII_run01_GRCh38.hic "results/refgenome/HindIII_GRCh38.rg.chromsizes"`

Be well,

Matt Pendleton

**Comment by antarikshtyagi** [comment]
Thanks for your reply. The script worked fine with smaller data but now dor larger dataset I am getting out of memory errors:

WARN [2020-08-11T21:39:01,477]  [Globals.java:138] [main]  Development mode is enabled
Using 12 CPU thread(s)
Start preprocess
Writing header
Writing body
.Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.Double.valueOf(Double.java:519)
        at juicebox.tools.utils.original.ExpectedValueCalculation.addDistance(ExpectedValueCalculation.java:167)
        at juicebox.tools.utils.original.MatrixZoomDataPP.incrementCount(MatrixZoomDataPP.java:174)
        at juicebox.tools.utils.original.MatrixPP.incrementCount(MatrixPP.java:131)
        at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:725)
        at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:425)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:139)
        at juicebox.tools.HiCTools.main(HiCTools.java:94)

WARN [2020-08-11T17:19:15,308]  [Globals.java:138] [main]  Development mode is enabled
Using 8 CPU thread(s)
Start preprocess
Writing header
Writing body
.Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at java.lang.String.substring(String.java:1969)
        at java.lang.String.subSequence(String.java:2003)
        at java.util.regex.Pattern.split(Pattern.java:1216)
        at java.lang.String.split(String.java:2380)
        at java.lang.String.split(String.java:2422)
        at juicebox.tools.clt.JuiceboxCLT.splitToList(JuiceboxCLT.java:47)
        at juicebox.tools.utils.original.AsciiPairIterator.advance(AsciiPairIterator.java:125)
        at juicebox.tools.utils.original.AsciiPairIterator.next(AsciiPairIterator.java:287)
        at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:673)
        at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:425)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:139)
        at juicebox.tools.HiCTools.main(HiCTools.java:94)

Please let me know how to fix these. Can the input *hic.txt file be split as a workaround for this error?

Thanks

**Comment by proinde** [comment]
If I recall, this is a java memory allocation issue. Using `-Xmx4g` instead of `-Xmx2g` would increase the maximum heap size for juicer_tools from 2GB to 4GB.

I don't believe that there exists a tool in the juicer universe that facilitates merging of converted  .hic files, so splitting the text files up and merging them following conversion is not possible without a significant coding effort on your part.
