### ISSUE TITLE
pipeline crashes - snappy not installed

### ISSUE THREAD

**Issue by dikkeaap** [nanoporetech/Pore-C-Snakemake#6]
Hi,

I'm trying to run the pore-c pipeline on an in-house generated dataset. I have installed the Pore-C and Pore-C-Snakemake conda environments as instructed. 

I have used the following commands:

conda env create
conda activate pore_c_snakemake
(edited the basecalls.tsv and config.yaml files to use the appropriate files and resources)
snakemake --use-conda --cores 24

This ran for a while, then gave the following error in one of the log files:
(results/logs/results/align_table/DpnII_run01_F1.at.catalog.yaml.log)

```
Traceback (most recent call last):
  File "/home/eda/tools/miniconda3/envs/poreC/bin/pore_c", line 33, in <module>
    sys.exit(load_entry_point('pore-c', 'console_scripts', 'pore_c')())
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/interos/eda/tools/pore-c/src/pore_c/cli.py", line 235, in parse
    fragment_df = vd_cat.fragments.read()
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/intake_parquet/source.py", line 78, in read
    return self._df.compute()
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 273,
    dfs = [func(fs, rg, columns.copy(), index, **kwargs) for rg in part]
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 273,
    dfs = [func(fs, rg, columns.copy(), index, **kwargs) for rg in part]
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py", lin
    rg_piece, columns, categories, index=index, **kwargs.get("read", {})
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/fastparquet/api.py", line 210, in read_row_gro
    assign=assign, scheme=self.file_scheme)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/fastparquet/core.py", line 306, in read_row_gr
    scheme=scheme)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/fastparquet/core.py", line 355, in read_row_gr
    cats, selfmade, assign=assign)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/fastparquet/core.py", line 332, in read_row_gr
    catdef=out.get(name+'-catdef', None))
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/fastparquet/core.py", line 199, in read_col
    dic = np.array(read_dictionary_page(infile, schema_helper, ph, cmd))
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/fastparquet/core.py", line 157, in read_dictio
    raw_bytes = _read_page(file_obj, page_header, column_metadata)
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/fastparquet/core.py", line 25, in _read_page
    column_metadata.codec,
  File "/home/eda/tools/miniconda3/envs/poreC/lib/python3.7/site-packages/fastparquet/compression.py", line 128, in deco
    (algorithm.upper(), sorted(decompressions)))
RuntimeError: Decompression 'SNAPPY' not available.  Options: ['BROTLI', 'GZIP', 'UNCOMPRESSED']
```

I tried resolving this by

conda install python-snappy

But that gave an error:

```
UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment:

Specifications:

  - cryptography -> python[version='<=3.3']
  - pandas==0.25.1 -> python[version='>=2.7,<2.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
  - python-dateutil -> python[version='>=3.8,<3.9.0a0']
  - urllib3 -> python[version='<=3.3']

Your python: python==3.6

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

followed by a loooong list of package conflicts. I'm not that familiar with conda; what can I do to resolve this?

**Comment by Priyesh000** [comment]
Hi there, 

I believe the issue is that you need to install python-snappy however, you could be installing python-snappy in the wrong environment. Please let us know if the following works for you 

```
conda activate poreC
conda install python-snappy 
conda deactivate 
```

Best,
Priyesh

**Comment by dikkeaap** [comment]
Hi Priyesh, thanks for your reply.I succesfully installed python-snappy in the poreC conda environment (after conda config --set channel_priority flexible; I had initially set it to strict to solve antoher issue). I am currently rerunning the analysis.
